# Generated by Django 3.1 on 2020-08-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_Name', models.CharField(max_length=50)),
                ('E_mail', models.CharField(max_length=30)),
                ('Username', models.CharField(max_length=20, unique=True)),
                ('Password', models.CharField(max_length=20)),
                ('Phone', models.IntegerField(max_length=15)),
                ('Address', models.TextField(max_length=100)),
            ],
        ),
    ]
