# Generated by Django 3.1 on 2020-08-19 09:00

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Phone',
            field=models.IntegerField(verbose_name=builtins.max),
        ),
    ]
