# Generated by Django 3.1 on 2020-08-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200819_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Phone',
            field=models.CharField(max_length=15),
        ),
    ]
